### ISSUE TITLE
Improve Cards that show details

### ISSUE THREAD

**Issue by Pjha72** [Pjha72/Hactoberfest_Catchy-Beatz#8]

**Comment by devanshukd04** [comment]
I will like to work on this issue

**Comment by Pjha72** [comment]
[devanshukd04](https://github.com/devanshukd04) okk

**Comment by ginabeki** [comment]
I would love to work on this issue

**Comment by devanshukd04** [comment]
Completed the issue #20

**Comment by Pjha72** [comment]
Not completed

**Comment by Shreyas-SAS** [comment]
@Pjha72 is this issue open? If so, please assign it to me. I will work on it.
