### ISSUE TITLE
Make a New Page for Hollywood Song

### ISSUE THREAD

**Issue by Pjha72** [Pjha72/Hactoberfest_Catchy-Beatz#9]

**Comment by riyaku11** [comment]
I would like to work on this issue

**Comment by riyaku11** [comment]
shall I make a new option for hollywood in the sidebar??

**Comment by Pjha72** [comment]
[riyaku11](https://github.com/riyaku11) No, You Can Make a New Page For Hollywood.
When Click on View All Button Then See All The Hollywood songs.

**Comment by riyaku11** [comment]
okay @Pjha72

**Comment by riyaku11** [comment]
done @Pjha72 , please check

**Comment by riyaku11** [comment]
@Pjha72  please check and accept my pull request
